In [1]:
%pip install pandas 
%pip install numpy
%pip install matplotlib
%pip install seaborn

Requirement already satisfied: pandas in a:\anacondaaa\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in a:\anacondaaa\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in a:\anacondaaa\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in a:\anacondaaa\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in a:\anacondaaa\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in a:\anacondaaa\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in a:\anacondaaa\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in a:\anacondaaa\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in a:\anacondaaa\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in a:\anacondaaa\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in a:\anacondaaa\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in a:\anacondaaa\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in a:\anacondaaa\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in a:\anacondaaa\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in a:\anacondaaa\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in a:\anacondaaa\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in a:\anacondaaa\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in a:\anacondaaa\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in a:\anacondaaa\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in a:\anacondaaa\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in a:\anacondaaa\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in a:\anacondaaa\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in a:\anacondaaa\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in a:\anacondaaa\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in a:\anacondaaa\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in a:\anacondaaa\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("atmosync_dataset.csv")

In [4]:
df.head()

,reading_id,container_id,commodity,timestamp,hours_in_transit,temperature_c,humidity_pct,vibration_g,ideal_temp_min_c,ideal_temp_max_c,...,quality_score,shelf_life_hours_remaining,primary_price_per_kg_usd,secondary_price_per_kg_usd,primary_net_value_usd,secondary_net_value_usd,arbitrage_gain_usd,risk_status,recommended_action,cooling_unit_faulty
0,1,CONT-0001,Avocado,2026-07-03 17:23:04.628550,0.0,5.31,88.29,0.220,4,7,...,99.98,2041.8,3.566,3.198,47306.56,42424.67,-4881.89,Normal,Continue to Primary Market,False
1,2,CONT-0001,Avocado,2026-07-03 17:53:04.628550,0.5,5.99,92.25,0.187,4,7,...,99.95,2066.2,3.564,3.197,47280.02,42411.40,-4868.62,Normal,Continue to Primary Market,False
2,3,CONT-0001,Avocado,2026-07-03 18:23:04.628550,1.0,5.10,88.08,0.220,4,7,...,99.93,2040.8,3.563,3.196,47266.76,42398.14,-4868.62,Normal,Continue to Primary Market,False
3,4,CONT-0001,Avocado,2026-07-03 18:53:04.628550,1.5,5.41,88.64,0.248,4,7,...,99.90,2019.8,3.562,3.195,47253.49,42384.87,-4868.62,Normal,Continue to Primary Market,False
4,5,CONT-0001,Avocado,2026-07-03 19:23:04.628550,2.0,5.28,89.30,0.193,4,7,...,99.88,2060.8,3.560,3.194,47226.96,42371.60,-4855.36,Normal,Continue to Primary Market,False

In [5]:
df.shape

(50000, 30)

In [7]:
df.describe()

,reading_id,hours_in_transit,temperature_c,humidity_pct,vibration_g,ideal_temp_min_c,ideal_temp_max_c,ideal_humidity_min_pct,ideal_humidity_max_pct,temp_deviation_c,...,distance_primary_km,distance_secondary_km,quantity_kg,quality_score,shelf_life_hours_remaining,primary_price_per_kg_usd,secondary_price_per_kg_usd,primary_net_value_usd,secondary_net_value_usd,arbitrage_gain_usd
count,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,24.59565,6.624175,89.974576,0.170556,4.938820,7.346540,87.213600,93.74220,0.391349,...,1825.533000,664.623000,14088.139880,95.605646,1600.255276,2.981790,2.645452,41615.825001,36916.919913,-4698.905087
std,14433.901067,14.43875,5.710725,3.228729,0.188111,5.355794,5.583837,2.483566,2.16957,1.309178,...,283.521822,375.002041,3578.548053,12.127313,776.474637,1.487501,1.311662,23481.561102,20729.788117,3302.703317
min,1.000000,0.00000,-2.710000,73.840000,0.000000,-1.000000,1.000000,85.000000,90.00000,0.000000,...,1400.000000,200.000000,8009.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-21938.430000
25%,12500.750000,12.00000,0.980000,87.870000,0.097000,0.000000,2.000000,85.000000,90.00000,0.000000,...,1600.000000,300.000000,10962.000000,97.340000,1147.100000,1.839000,1.613000,23435.125000,21034.385000,-6533.730000
50%,25000.500000,24.50000,5.590000,90.190000,0.151000,4.000000,7.000000,85.000000,95.00000,0.000000,...,1800.000000,600.000000,14259.000000,98.400000,1703.300000,2.833000,2.519000,37010.970000,32863.870000,-3988.250000
75%,37500.250000,37.00000,11.800000,92.300000,0.206000,10.000000,13.000000,90.000000,95.00000,0.000000,...,2100.000000,900.000000,17247.000000,99.220000,2201.925000,4.139000,3.648000,54472.047500,48498.015000,-2508.800000
max,50000.000000,49.50000,24.170000,99.000000,2.486000,13.000000,15.000000,90.000000,95.00000,9.750000,...,2300.000000,1400.000000,19965.000000,99.980000,2853.200000,6.416000,5.832000,126614.880000,109314.830000,7479.900000

In [8]:
df.columns

Index(['reading_id', 'container_id', 'commodity', 'timestamp',
       'hours_in_transit', 'temperature_c', 'humidity_pct', 'vibration_g',
       'ideal_temp_min_c', 'ideal_temp_max_c', 'ideal_humidity_min_pct',
       'ideal_humidity_max_pct', 'temp_deviation_c', 'humidity_deviation_pct',
       'origin_port', 'primary_market', 'secondary_market',
       'distance_primary_km', 'distance_secondary_km', 'quantity_kg',
       'quality_score', 'shelf_life_hours_remaining',
       'primary_price_per_kg_usd', 'secondary_price_per_kg_usd',
       'primary_net_value_usd', 'secondary_net_value_usd',
       'arbitrage_gain_usd', 'risk_status', 'recommended_action',
       'cooling_unit_faulty'],
      dtype='object')

In [9]:
df.dtypes

reading_id                      int64
container_id                   object
commodity                      object
timestamp                      object
hours_in_transit              float64
temperature_c                 float64
humidity_pct                  float64
vibration_g                   float64
ideal_temp_min_c                int64
ideal_temp_max_c                int64
ideal_humidity_min_pct          int64
ideal_humidity_max_pct          int64
temp_deviation_c              float64
humidity_deviation_pct        float64
origin_port                    object
primary_market                 object
secondary_market               object
distance_primary_km             int64
distance_secondary_km           int64
quantity_kg                     int64
quality_score                 float64
shelf_life_hours_remaining    float64
primary_price_per_kg_usd      float64
secondary_price_per_kg_usd    float64
primary_net_value_usd         float64
secondary_net_value_usd       float64
arbitrage_gain_usd            float64
risk_status                    object
recommended_action             object
cooling_unit_faulty              bool
dtype: object